# Site settings
title: 夜禹
description: '不积跬步无以至千里，不积小流无以成江海'
url: 'http://yemingyu.com' 
baseurl: '/'
google_analytics: 'UA-501066-1'

author:
  name: '夜禹'
  email: me@yemingyu.com
  twitter_username: yemingyu
  github_username:  yemingyu
  linkedin_username:  yemingyu

# Build settings
destination: _site
paginate: 10
#paginate_path: "/blog/page:num"
permalink: /blog/:year/:month/:day/:title/
#permalink: "page:num"
markdown: kramdown
highlighter: pygments
excerpt_separator: "\n\n\n"

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'src']